// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";


// đây là cấu hỉnh cho prisma CLI (dev-time) không phải runtime config của app
// khi chạy:
// npx prisma migrate dev
// npx prisma migrate deploy
// npx prisma generate
export default defineConfig({
  // CLI đọc file này để generate client, sinh migration, validate schema
  schema: "prisma/schema.prisma",
  // nơi Prisma lưu:
  //   SQL migration
  //   Lịch sử schema
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seeds/permission.seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
