export enum ErrorCode {
  // Common errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // Auth specific errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  OTP_INVALID = 'OTP_INVALID',
  GOOGLE_AUTH_REQUIRED = 'GOOGLE_AUTH_REQUIRED',
  PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  GOOGLE_PROFILE_INCOMPLETE = 'GOOGLE_PROFILE_INCOMPLETE',
  GOOGLE_ACCOUNT_ALREADY_LINKED = 'GOOGLE_ACCOUNT_ALREADY_LINKED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  PASSWORD_ALREADY_EXISTS = 'PASSWORD_ALREADY_EXISTS',
  PASSWORD_NOT_SET = 'PASSWORD_NOT_SET',
  OLD_PASSWORD_INCORRECT = 'OLD_PASSWORD_INCORRECT',
  NEW_PASSWORD_SAME_AS_OLD = 'NEW_PASSWORD_SAME_AS_OLD',
  INVALID_OTP = 'INVALID_OTP',
  GOOGLE_EMAIL_NOT_FOUND = 'GOOGLE_EMAIL_NOT_FOUND',
  // Database specific errors
  DATABASE_ERROR = 'DATABASE_ERROR',
  DUPLICATE_VALUE = 'DUPLICATE_VALUE',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  FOREIGN_KEY_FAILED = 'FOREIGN_KEY_FAILED',

  // BLOG
  BLOG_NOT_FOUND = 'BLOG_NOT_FOUND',
  BLOG_ACCESS_FORBIDDEN = 'BLOG_ACCESS_FORBIDDEN',
  BLOG_EDIT_FORBIDDEN = 'BLOG_EDIT_FORBIDDEN',
  BLOG_DELETE_FORBIDDEN = 'BLOG_DELETE_FORBIDDEN',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_EDIT_FORBIDDEN = 'COMMENT_EDIT_FORBIDDEN',
  COMMENT_DELETE_FORBIDDEN = 'COMMENT_DELETE_FORBIDDEN',

  // GRAMMAR
  GRAMMAR_NOT_FOUND = 'GRAMMAR_NOT_FOUND',
  GRAMMAR_EDIT_FORBIDDEN = 'GRAMMAR_EDIT_FORBIDDEN',
  GRAMMAR_DELETE_FORBIDDEN = 'GRAMMAR_DELETE_FORBIDDEN',

  // CHAT
  GROUP_NOT_FOUND_OR_INACTIVE = 'GROUP_NOT_FOUND_OR_INACTIVE',
  GROUP_MEMBER_FORBIDDEN = 'GROUP_MEMBER_FORBIDDEN',
  ONLY_OWNER_ALLOWED = 'ONLY_OWNER_ALLOWED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  GROUP_MEMBER_NOT_FOUND = 'GROUP_MEMBER_NOT_FOUND',
  SOME_MEMBERS_NOT_FOUND = 'SOME_MEMBERS_NOT_FOUND',
  ALL_MEMBERS_ALREADY_EXISTS = 'ALL_MEMBERS_ALREADY_EXISTS',
  CANNOT_CHANGE_GROUP_OWNER_ROLE = 'CANNOT_CHANGE_GROUP_OWNER_ROLE',
  CANNOT_DEMOTE_SELF = 'CANNOT_DEMOTE_SELF',
  CANNOT_CHANGE_HIGHER_ROLE = 'CANNOT_CHANGE_HIGHER_ROLE',
  CANNOT_CHANGE_SAME_LEVEL_ROLE = 'CANNOT_CHANGE_SAME_LEVEL_ROLE',
  PERMISSION_RECORDS_NOT_FOUND = 'PERMISSION_RECORDS_NOT_FOUND',
  ONLY_GROUP_OWNER_CAN_DELETE = 'ONLY_GROUP_OWNER_CAN_DELETE',
  GROUP_INACTIVE_OR_NOT_FOUND = 'GROUP_INACTIVE_OR_NOT_FOUND',
  ALREADY_GROUP_MEMBER = 'ALREADY_GROUP_MEMBER',
  OWNER_CANNOT_LEAVE_GROUP = 'OWNER_CANNOT_LEAVE_GROUP',
  CANNOT_REMOVE_GROUP_OWNER = 'CANNOT_REMOVE_GROUP_OWNER',
  ONLY_OWNER_CAN_TRANSFER_OWNERSHIP = 'ONLY_OWNER_CAN_TRANSFER_OWNERSHIP',
  NEW_OWNER_MUST_BE_MEMBER = 'NEW_OWNER_MUST_BE_MEMBER',
  GROUP_NAME_REQUIRED = 'GROUP_NAME_REQUIRED',

  // MESSAGE
  RECEIVER_ID_REQUIRED = 'RECEIVER_ID_REQUIRED',
  GROUP_ID_REQUIRED = 'GROUP_ID_REQUIRED',
  MESSAGE_CONTENT_OR_ATTACHMENTS_REQUIRED = 'MESSAGE_CONTENT_OR_ATTACHMENTS_REQUIRED',
  MESSAGE_TARGET_REQUIRED = 'MESSAGE_TARGET_REQUIRED',
  CANNOT_CHAT_WITH_USER = 'CANNOT_CHAT_WITH_USER',
  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',

  // UPLOAD
  UPLOAD_FILE_REQUIRED = 'UPLOAD_FILE_REQUIRED',

  // USER
  USER_NOT_FOUND_BY_USERNAME = 'USER_NOT_FOUND_BY_USERNAME',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  PRIVATE_POST_ACCESS_DENIED = 'PRIVATE_POST_ACCESS_DENIED',
  PRIVATE_FOLLOWERS_ACCESS_DENIED = 'PRIVATE_FOLLOWERS_ACCESS_DENIED',
  PRIVATE_FOLLOWING_ACCESS_DENIED = 'PRIVATE_FOLLOWING_ACCESS_DENIED',
  PRIVATE_FRIENDS_ACCESS_DENIED = 'PRIVATE_FRIENDS_ACCESS_DENIED',
  FOLLOW_ACCESS_DENIED = 'FOLLOW_ACCESS_DENIED',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',
  CANNOT_UNFOLLOW_SELF = 'CANNOT_UNFOLLOW_SELF',
  LINK_EDIT_PERMISSION_DENIED = 'LINK_EDIT_PERMISSION_DENIED',
  LINK_DELETE_PERMISSION_DENIED = 'LINK_DELETE_PERMISSION_DENIED',
  CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF',
  CANNOT_UNBLOCK_SELF = 'CANNOT_UNBLOCK_SELF',

  // VOCABULARY
  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  COLLECTION_ID_REQUIRED = 'COLLECTION_ID_REQUIRED',
  CARD_TYPE_NOT_FOUND = 'CARD_TYPE_NOT_FOUND',
  DUPLICATE_FIELD_DATA = 'DUPLICATE_FIELD_DATA',
  FIELD_NOT_IN_CARD_TYPE = 'FIELD_NOT_IN_CARD_TYPE',
  ALL_FIELDS_EMPTY = 'ALL_FIELDS_EMPTY',
  CARD_NOT_FOUND_OR_FORBIDDEN = 'CARD_NOT_FOUND_OR_FORBIDDEN',
  CARD_TYPE_FIELDS_UNDEFINED = 'CARD_TYPE_FIELDS_UNDEFINED',

  // ENV
  INVALID_ENVIRONMENT_VARIABLES = 'INVALID_ENVIRONMENT_VARIABLES',
}
