export enum GroupPermission {
  UPDATE_GROUP_INFO = 'UPDATE_GROUP_INFO',
  ADD_MEMBER = 'ADD_MEMBER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  MANAGE_ROLES = 'MANAGE_ROLES',
  DELETE_GROUP = 'DELETE_GROUP',
}
