const PERMISSION_GROUP = {
  // Member Management
  ADD_MEMBER: 'ADD_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  UPDATE_MEMBER_ROLE: 'UPDATE_MEMBER_ROLE',
  ADD_ADMIN: 'ADD_ADMIN',
  REMOVE_ADMIN: 'REMOVE_ADMIN',

  // Group Information
  UPDATE_GROUP_NAME: 'UPDATE_GROUP_NAME',
  UPDATE_GROUP_DESCRIPTION: 'UPDATE_GROUP_DESCRIPTION',
  UPDATE_GROUP_AVATAR: 'UPDATE_GROUP_AVATAR',

  // Group Lifecycle
  DELETE_GROUP: 'DELETE_GROUP',
} as const

export default PERMISSION_GROUP
